@echo off


set BINDIR=build\bin\x86
set OBJDIR=build\obj

set EXECUTABLE=df.exe



set COMMON_COMPILER_FLAGS=/D WIN32 /D _WIN32_WINNT=0x0600 /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /I . /I %FUSION_PATH%\include /I %POISSON_RECON_PATH%\Src /W4 /wd4100 /wd4101 /wd4127 /wd4189 /wd4201 /wd4251 /wd4505 /wd4702 /D_CRT_SECURE_NO_WARNINGS /FC /EHsc /GR- /nologo
set COMMON_LINKER_FLAGS=/LIBPATH:%FUSION_PATH%\lib\x86 /OUT:..\%BINDIR%\%EXECUTABLE% /OPT:REF /INCREMENTAL:NO /SUBSYSTEM:CONSOLE

set DEBUG_COMPILER_FLAGS=/Od /Ob0 /Oi /Zi /MDd /D_DEBUG %COMMON_COMPILER_FLAGS%
set RELEASE_COMPILER_FLAGS=/O2 /Ob2 /Oi /MD %COMMON_COMPILER_FLAGS%

IF NOT EXIST %BINDIR% mkdir %BINDIR%
IF NOT EXIST %OBJDIR% mkdir %OBJDIR%

pushd %OBJDIR%

REM cl %DEBUG_COMPILER_FLAGS% ..\src\main.cpp /link %COMMON_LINKER_FLAGS% Fusion.lib
cl %RELEASE_COMPILER_FLAGS% ..\..\main.cpp /link %COMMON_LINKER_FLAGS%

set lasterror=%errorlevel%

popd
